---
apiVersion: v1
kind: Service
metadata:
  name: mutateme
  labels:
    app: mutateme
spec:
  publishNotReadyAddresses: true
  ports:
    - port: 443
      targetPort: 8443
  selector:
    app: mutateme

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mutateme
  labels:
    app: mutateme
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mutateme
  template:
    metadata:
      name: mutateme
      labels:
        app: mutateme
    spec:
      containers:
        - name: mutator
          image: registry.us-west-1.aliyuncs.com/apphub/test-mutate:latest
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 250m
              memory: 64Mi

---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  name: mutateme
  labels:
    app: mutateme
webhooks:
  - name: mutateme.rzhang.alibaba.com
#    objectSelector:
#      matchLabels:
#        app: mutate-test
    clientConfig:
      # kubectl config view --raw --minify --flatten -o jsonpath='{.clusters[].cluster.certificate-authority-data}'
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURHakNDQWdLZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREErTVNjd0ZBWURWUVFLRXcxaGJHbGkKWVdKaElHTnNiM1ZrTUE4R0ExVUVDaE1JYUdGdVozcG9iM1V4RXpBUkJnTlZCQU1UQ210MVltVnlibVYwWlhNdwpIaGNOTWpBd01URXdNREkxTlRVMldoY05NekF3TVRBM01ESTFOVFUyV2pBK01TY3dGQVlEVlFRS0V3MWhiR2xpCllXSmhJR05zYjNWa01BOEdBMVVFQ2hNSWFHRnVaM3BvYjNVeEV6QVJCZ05WQkFNVENtdDFZbVZ5Ym1WMFpYTXcKZ2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRRElXbmYwODBIWmk2OUdIakRHNGVMRwpqbzl2NDdPR3hpVmlNekN4VFY2clJlREdzYmlDSC8xQ2s5dzMzczJXRVRBRkxiTGVwSHU4Z1RaZEY1OXR2UDh2ClRDZ0NpVTVnYTRPdmZUbjNFSXlZL2JIbGZCaWFFeHkyb0d5VEVvMkxPUTF3bTV5VHF5MVVXTlQwQTJUc0JWcDMKRGIvWUp6RW5TdzAxWHFDSHV6aGwyQUh1OHhodExzeWVmYmlWVHAyTnZyOFFQRHNUMXFVVW9MTjFabVNkemVVTgpuZ2tJQnVOWVFUcmNGQnc3TktpSUpvZHJsRk5HY25oZWsvWmNOeGpFcVJYUXVWSGpKOEc2T0cyUy9GQkY3S1pqClhEMGNRamdXcEwzTk5ObFQ0NW53a3d4eVJRVUZvdmQ3YmxyYmJQWkd6U2Z4MHRUNWpFVktXUTZPMDdsUElsSFYKQWdNQkFBR2pJekFoTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQQmdOVkhSTUJBZjhFQlRBREFRSC9NQTBHQ1NxRwpTSWIzRFFFQkN3VUFBNElCQVFDWnVSTW9OQUFFTDlnVlh5Q0FWS0ovR1lFM1QxcjVDb1R4RVFqVVdVYW9QazFYCkc5eC9ZbnlOZGF6VEZMUm15eW1aTHFGTEUzd05kVUFiMk9EdytDY045S2ZiTWg1Tlk4ajBBR0VoVE1wOGNGZ0oKQlJMU25XSnBYR1p5TVI1Q2xTK0NVT0ZiSnRJbUZkanQ2dVAzN1ZNZi9RRy80ckV1SEQwWUVxaFNReG5zZXpLaApJY0p6bHUrTWhJdXdzNDN0clBqbTRybVluYU1zTGZDSmgwaEdzVmRnbVcxaTN5UzllOUpreW02bDFQK0pnMWN6ClJFSjRnQWlGWE8yeW5ScS8zeGVlY3FoZUx2eFdTaFR3MFBzanNrZnRuWTdoTDFJTlIzeWxINjY5cTRPcnJqQjYKZ2MyeVlWN0FkOENRQ2FiWEVHa1BEeGZ6cVFVdmFOb2t1ZmREczlOUwotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
      service:
        name: mutateme
        namespace: default
        path: "/mutate"
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
    namespaceSelector:
      matchLabels:
        mutateme: enabled
